trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    terraform version
  displayName: 'Check Terraform'

- script: |
    terraform init
  displayName: 'Terraform Init'

- script: |
    terraform validate
  displayName: 'Terraform Validate'

- task: AzureCLI@2
  displayName: 'Terraform Plan'
  inputs:
    azureSubscription: 'JupiterAI-Azure-Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      export ARM_USE_CLI=true

      terraform plan \
        -input=false \
        -var="resource_group_name=JupiterAI-RG" \
        -var="location=Central India" \
        -var="storage_account_name=jupiterai2026storage" \
        -var="environment=Dev"