- task: AzureCLI@2
  displayName: 'Terraform Plan'
  inputs:
    azureSubscription: 'JupiterAI-Azure-Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform plan \
        -input=false \
        -var="resource_group_name=JupiterAI-RG" \
        -var="location=Central India" \
        -var="storage_account_name=jupiterai2026storage" \
        -var="environment=Dev"