trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    terraform version
  displayName: 'Check Terraform'

- script: |
    terraform init
  displayName: 'Terraform Init'

- script: |
    terraform validate
  displayName: 'Terraform Validate'